services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homey
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - 80:80
      - 3000:3000
    env_file:
      - .env
    networks:
      - homey-net
    volumes:
      - '.:/app'
    depends_on:
      - pgsqldb
  pgsqldb:
    env_file:
      - .env
    container_name: pgsqldb
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: ${APP_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - homey-net
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
    homey-net:
        driver: bridge
volumes:
    pgdata:
      driver: local